- name: 1. install MySQL Server
  apt: name=mysql-server state=present update_cache=yes

- name: 2. install MySQL Client
  apt: name=mysql-client state=present update_cache=yes

- name: 3. Start Mysql Service
  service: name=mysql state=started enabled=true

- name: 4. Install MySQL extension for PHP
  apt: name=php5-mysql state=present
